/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiapp;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jsepulveda
 */
public class ListarTotalesAlumnos extends javax.swing.JFrame {

    /**
     * Creates new form ListarTotalesAlumnos
     */
    public ListarTotalesAlumnos() {
        initComponents();
        Matricula_FileHandler mfh = new Matricula_FileHandler("Matriculas.csv");
        Carrera_FileHandler cfh = new Carrera_FileHandler("Carreras.csv");
        String matriculas[][];
        matriculas = mfh.LeerMatricula();
        Object columnNames[] = { "Carrera", "Cantidad Alumnos", "Total Recaudado" };
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);
        
        String Lista_Carreras[][];
        String txt_Carrera;
        Lista_Carreras = cfh.LeerCarrera();
        
        String Lista_matriculas [][];
        String txt_Carrera_2;
        
        Lista_matriculas = mfh.LeerMatricula();
        //For para la lista de carreras
        
        int contador_alumnos;
        int suma_carrera;
        String [] Row = new String[3];
        
        for (int i=0;i<Lista_Carreras.length;i++){
            txt_Carrera = Lista_Carreras[i][0];
            contador_alumnos=0;
            suma_carrera=0;
            Row[0]="";
            Row[1]="";
            Row[2]="";
            for (int j=0;j<Lista_matriculas.length;j++){
                txt_Carrera_2 = Lista_matriculas[j][2];
                System.out.println("Carrera1: "+txt_Carrera);
                System.out.println("Carrera2: "+txt_Carrera_2);
                if(txt_Carrera.equals(txt_Carrera_2)){
                    //Agregar SUMA
                    //Agregar Contador
                    suma_carrera =suma_carrera + Integer.parseInt(Lista_matriculas[j][3]);
                    contador_alumnos +=1;
                    
                    System.out.println("Suma: "+Integer.parseInt(Lista_matriculas[j][3]));
                    System.out.println("Cantidad Alumnos: "+contador_alumnos);
                }
            }
            //Agregar Row
                Row[0]=txt_Carrera;
                Row[1]=String.valueOf(contador_alumnos);
                Row[2]=String.valueOf(suma_carrera);
                System.out.println("----------");
                System.out.println("Carrera: "+txt_Carrera);
                System.out.println("Alumnos: "+contador_alumnos);
                System.out.println("Total: "+suma_carrera);
                System.out.println("----------");
                model.addRow(Row);
                contador_alumnos=0;
                suma_carrera=0;
        }
        
        jTable1.setModel(model);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Carrera");

        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jButton1)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarTotalesAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarTotalesAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarTotalesAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarTotalesAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarTotalesAlumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
