/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author rgonzalez
 */
public class Form_VentaPasajes extends javax.swing.JFrame {

    /**
     * Creates new form Form_VentaPasajes
     */
    public Form_VentaPasajes() {
        initComponents();
        LlenarCodigosViajes();
        LlenarRutVendedores();
        Ponerfolio(GenerarFolio());
        txtPrecio.disable();
        txtFolio.disable();
        txtFechaVenta.setText(GetFechaActual());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFolio = new javax.swing.JTextField();
        txtFechaVenta = new javax.swing.JTextField();
        cbxCodigoViaje = new javax.swing.JComboBox<>();
        cbxRutVendedor = new javax.swing.JComboBox<>();
        txtPrecio = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Venta de pasajes");

        jLabel2.setText("Codigo de Viaje");

        jLabel3.setText("Folio");

        jLabel4.setText("Fecha Venta");

        jLabel5.setText("Rut Vendedor");

        jLabel6.setText("Precio");

        txtFechaVenta.setText("DD/MM/AAAA");

        cbxCodigoViaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        cbxCodigoViaje.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCodigoViajeItemStateChanged(evt);
            }
        });
        cbxCodigoViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCodigoViajeActionPerformed(evt);
            }
        });

        cbxRutVendedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(86, 86, 86)
                        .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFechaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxRutVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxCodigoViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxCodigoViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFechaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbxRutVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(jButton2))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
        if (ValidarCampos()){
            String  FechaVenta,RutVendedor;
            int Folio,CodigoViaje,Precio;
            Folio = Integer.parseInt(txtFolio.getText());
            if (!ValidarFolio(Folio)){
                //Calcular CodigoViaje
                String CodViaje = cbxCodigoViaje.getSelectedItem().toString();
                String[] parts = CodViaje.split(" -");
                System.out.println("Codigo Viaje: "+parts[0]);
                
                if (ValidarCantAsientos(Integer.parseInt(parts[0]))){
                    FechaVenta = txtFechaVenta.getText();
                    Precio = Integer.parseInt(txtPrecio.getText());
                    //CodigoViaje=Integer.parseInt(cbxCodigoViaje.getSelectedItem().toString());
                    CodigoViaje=Integer.parseInt(parts[0]);
                    RutVendedor = cbxRutVendedor.getSelectedItem().toString();
                    ClassMysql MysqlHandler= new ClassMysql();
                    String Query;
                    Query = "INSERT INTO `venta_pasajes` VALUES ('"+Folio+"','"+CodigoViaje+"','"+FechaVenta+"','"+RutVendedor+"','"+Precio+"')";
                    System.out.println(Query);
                    MysqlHandler.EjecutarQuery(Query);
                    //Realizar descuento de PasajesDisponibles
                    int CantidadAsientosDisponibles = GetCantAsientosDisponibles(CodigoViaje);
                    System.out.println(CantidadAsientosDisponibles);
                    String QueryUpdAsientos;
                    QueryUpdAsientos ="UPDATE `viajes` set PasajesDisponibles='"+(CantidadAsientosDisponibles -1)+"' WHERE CodigoViaje='"+CodigoViaje+"'";
                    MysqlHandler.EjecutarQuery(QueryUpdAsientos);
                    JOptionPane.showMessageDialog(null, "Venta agregada");
                    dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "No existen pasajes disponibles.");
                }
            }else{
                JOptionPane.showMessageDialog(null, "El Folio ya existe.");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Hay que campos que necesitan ser validados.");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cbxCodigoViajeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCodigoViajeItemStateChanged
        // TODO add your handling code here:
        try{
            System.out.println("Item Changed");
        if (!cbxCodigoViaje.getSelectedItem().toString().isEmpty()){
            String CodViaje = cbxCodigoViaje.getSelectedItem().toString();
            //4321 - Santiago
            String[] parts = CodViaje.split(" -");
            //int CodViajeInt = Integer.parseInt(parts[0]);
            System.out.println("Codigo Viaje: "+parts[0]);
            int Precio = ObtenerPrecio(Integer.parseInt(parts[0]));
            txtPrecio.setText(String.valueOf(Precio));
        }
         }catch (Exception e){
            //System.out.println(e.printStackTrace());
            //e.printStackTrace();
        }
    }//GEN-LAST:event_cbxCodigoViajeItemStateChanged

    private void cbxCodigoViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCodigoViajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCodigoViajeActionPerformed
    
    private boolean ValidarCampos(){
        if (txtFolio.getText().isEmpty())
            return false;
        if (txtFechaVenta.getText().isEmpty())
            return false;
        if (txtPrecio.getText().isEmpty())
            return false;
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_VentaPasajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_VentaPasajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_VentaPasajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_VentaPasajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_VentaPasajes().setVisible(true);
            }
        });
    }
    
    private void LlenarCodigosViajes(){
        cbxCodigoViaje.addItem("Seleccionar Codigo de Viaje");
        try{
            ClassMysql MysqlHandler= new ClassMysql();
                String query;
                query = "select CodigoViaje,destino from `viajes`";
                Connection con = MysqlHandler.getCon();
                Statement stm = con.createStatement();
                ResultSet res = stm.executeQuery(query);
                while (res.next()){
                     cbxCodigoViaje.addItem(res.getString("CodigoViaje") +" - "+ res.getString("destino"));
                }
        }catch (SQLException e){
            System.out.println(e.getMessage());
        }
    }
    
    private void LlenarRutVendedores(){
        cbxRutVendedor.addItem("Seleccionar Rut Vendedor");
        try{
            ClassMysql MysqlHandler= new ClassMysql();
                String query;
                query = "select Rut_Vendedor from `vendedor`";
                Connection con = MysqlHandler.getCon();
                Statement stm = con.createStatement();
                ResultSet res = stm.executeQuery(query);
                while (res.next()){
                     cbxRutVendedor.addItem(res.getString("Rut_Vendedor"));
                }
        }catch (SQLException e){
            System.out.println(e.getMessage());
        }
    }
        
        private Boolean ValidarFolio(int Folio){
            try{
                ClassMysql MysqlHandler= new ClassMysql();
                String query;
                query = "SELECT Folio from `venta_pasajes` WHERE Folio ='"+Folio+"'";
                Connection con = MysqlHandler.getCon();
                Statement stm = con.createStatement();
                ResultSet res = stm.executeQuery(query);
                while (res.next()){
                    return true;
                }
            }catch (SQLException e){
                System.out.println(e.getMessage());
            }
            return false;    
            }
        
        private Boolean ValidarCantAsientos(int CodigoViaje){
            try{
                ClassMysql MysqlHandler= new ClassMysql();
                String query;
                query = "SELECT PasajesDisponibles from `viajes` WHERE CodigoViaje ='"+CodigoViaje+"'";
                Connection con = MysqlHandler.getCon();
                Statement stm = con.createStatement();
                ResultSet res = stm.executeQuery(query);
                int PasajesDisponibles;
                while (res.next()){
                    PasajesDisponibles = res.getInt("PasajesDisponibles");
                    if (PasajesDisponibles > 0)
                    return true;
                }
            }catch (SQLException e){
                System.out.println(e.getMessage());
            }
            return false; 
        }
        
        
        private int GetCantAsientosDisponibles(int CodigoViaje){
            try{
                ClassMysql MysqlHandler= new ClassMysql();
                String query;
                query = "SELECT PasajesDisponibles from `viajes` WHERE CodigoViaje ='"+CodigoViaje+"'";
                Connection con = MysqlHandler.getCon();
                Statement stm = con.createStatement();
                ResultSet res = stm.executeQuery(query);
                int PasajesDisponibles;
                while (res.next()){
                    return res.getInt("PasajesDisponibles");
                }
            }catch (SQLException e){
                System.out.println(e.getMessage());
            }
            return 0; 
        }
        private int ObtenerPrecio(int CodigoViaje){
            System.out.println("Obtener Precio:"+CodigoViaje);
            try{
                ClassMysql MysqlHandler= new ClassMysql();
                String query;
                query = "SELECT precio from `viajes` WHERE CodigoViaje ='"+CodigoViaje+"'";
                Connection con = MysqlHandler.getCon();
                Statement stm = con.createStatement();
                ResultSet res = stm.executeQuery(query);
                while (res.next()){
                    return res.getInt("precio");
                }
            }catch (SQLException e){
                System.out.println(e.getMessage());
            }
            return 0; 
        }
        
        private int GenerarFolio(){
             try{
                ClassMysql MysqlHandler= new ClassMysql();
                String query;
                query = "SELECT MAX(Folio) as Folio from `venta_pasajes`";
                Connection con = MysqlHandler.getCon();
                Statement stm = con.createStatement();
                ResultSet res = stm.executeQuery(query);
                int Folio=0;
                while (res.next()){
                    
                     if (res.getInt("Folio")>0)
                         return res.getInt("Folio")+1;
                     else
                         return 100001;
                }
            }catch (SQLException e){
                System.out.println(e.getMessage());
            }
             return 100001;
        }
        
        private void Ponerfolio(int Folio){
            txtFolio.setText(String.valueOf(Folio));
        }
        
        private String GetFechaActual (){
            Date date = Calendar.getInstance().getTime();
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            System.out.println(sdf.format(date));
            return sdf.format(date);
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxCodigoViaje;
    private javax.swing.JComboBox<String> cbxRutVendedor;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtFechaVenta;
    private javax.swing.JTextField txtFolio;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
